import React from 'react';

export const LegalPage: React.FC = () => {
  return (
    <div className="w-full max-w-3xl mx-auto px-4 py-12 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <h2 className="text-3xl font-bold text-slate-800 mb-8 text-center">Legal & Disclaimers</h2>
      
      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 text-slate-600 space-y-6">
        <section>
          <h3 className="text-lg font-bold text-[#1F2937] mb-2">1. Usage & Accuracy</h3>
          <p className="text-sm leading-relaxed text-justify">
            Camosnoop uses artificial intelligence to generate color palettes. While we strive for aesthetic excellence, the results are generated by AI and should be used as creative inspiration rather than absolute technical specifications. Camosnoop is provided "as is" without warranty of any kind, express or implied. We are not responsible for any design decisions or purchases made based on these suggestions.
          </p>
        </section>

        <section>
          <h3 className="text-lg font-bold text-[#1F2937] mb-2">2. Affiliate Disclosure</h3>
          <p className="text-sm leading-relaxed text-justify">
            Camosnoop is a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for sites to earn advertising fees by advertising and linking to Amazon.com. When you click on "Buy on Amazon" links within our application and make a purchase, we may earn a small commission at no extra cost to you. This helps support the development and maintenance of this free tool.
          </p>
        </section>

        <section>
          <h3 className="text-lg font-bold text-[#1F2937] mb-2">3. Trademarks & Intellectual Property</h3>
          <p className="text-sm leading-relaxed text-justify">
            "Pantone" is a registered trademark of Pantone LLC. "Golden" and "Heavy Body Acrylics" are trademarks of Golden Artist Colors, Inc. Camosnoop is not affiliated with, endorsed by, or sponsored by these companies. Any references to these brands are for comparison and informational purposes only. All generated color matches are approximations for creative reference.
          </p>
        </section>

        <section>
          <h3 className="text-lg font-bold text-[#1F2937] mb-2">4. User Content</h3>
          <p className="text-sm leading-relaxed text-justify">
            By uploading images to Camosnoop, you confirm that you have the right to use those images. Images are processed temporarily for the purpose of color extraction and are not stored permanently on our servers.
          </p>
        </section>
      </div>
    </div>
  );
};